# Generated by Django 3.1.3 on 2020-12-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanture_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hashtag',
            field=models.CharField(default='', max_length=20),
        ),
    ]
