# Generated by Django 3.1.3 on 2020-12-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advanture_app', '0002_article_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
    ]
