# Generated by Django 3.1.3 on 2020-12-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanture_app', '0004_auto_20201216_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAndEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/events')),
            ],
        ),
    ]
