# Generated by Django 3.1.3 on 2020-12-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanture_app', '0005_newsandevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='image',
            field=models.ImageField(upload_to='events'),
        ),
    ]
